### PR TITLE
Ignore empty lines when checking indentation

### LINKED ISSUE #115: Empty lines should not be indented
I would not expect any warnings or errors with the following code:

```
plugin.tx_gkhrssimport_pi1 = USER
plugin.tx_gkhrssimport_pi1 {
	userFunc = GertKaaeHansen\GkhRssImport\Controller\RssImportController->main

	templateFile = {$plugin.tx_gkhrssimport_pi1.templateFile}
}
```

but I get a warning that my indent on line 4 is wrong (the empy line) and expected to be 1 tab.

My requirement is that empty lines should always have no indent no matter where they are.

### PR DESCRIPTION
**Pull request by martin-helmich**
This fixes a regression caused by a change in a dependency (martin-helmich/typo3-typoscript-parser#61). That change made empty statements (read: empty lines) turn up in the token stream (which was on purpose, since it actually allows more insight into how the code was originally formatted before lexical analysis). Unfortunately, that messed up the IndentationSniff, which now also expected these empty lines to have indentation.

This change modifies the IndentationSniff to explicitly exclude empty lines from analysis.

Fixes #115

### CODE REVIEW

File: src/Linter/Sniff/IndentationSniff.php [hunk 1]
```diff
@@ -105,6 +108,14 @@ public function sniff(array $tokens, File $file, LinterConfiguration $configurat
...
     private function isEmptyLine(array $tokensInLine): bool
     {
+        $tokensInLine = array_values(array_filter($tokensInLine, function (TokenInterface $t): bool {
+            return $t->getType() !== TokenInterface::TYPE_EMPTY_LINE;
+        }));
+
+        if (count($tokensInLine) === 0) {
+            return true;
+        }
+
```
Comment (simonschaufi) [inline src/Linter/Sniff/IndentationSniff.php:118]: shouldn't there be just a return false? Can `$tokensInLine` also be exactly 1? In this case the method doesn't return anything instead of a boolean value and than it crashes.
